const K1 = 1.2;
const B = 0.75;
const TITLE_WEIGHT = 0.4;
const DESCRIPTION_WEIGHT = 0.3;
const TRANSCRIPT_WEIGHT = 0.2;
const TAG_WEIGHT = 0.1;

const DAMPING_FACTOR = 0.85;
const MAX_ITERATIONS = 10;

module.exports = {
  K1,
  B,
  TITLE_WEIGHT,
  DESCRIPTION_WEIGHT,
  TRANSCRIPT_WEIGHT,
  TAG_WEIGHT,
  DAMPING_FACTOR,
  MAX_ITERATIONS,
};
