const jsWords = [
  "javascript",
  "tailwind",
  "tailwindcss",
  "ecmascript",
  "ecma",
  "es6",
  "es5",
  "es4",
  "es3",
  "es2",
  "es1",
  "css",
  "html",
  "settimeout",
  "async",
  "nodejs",
  "js",
  "vue",
  "jquery",
  "express.js",
  "react",
  "angular",
  "vue.js",
  "jquery",
  "express.js",
  "next.js",
  "nuxt.js",
  "svelte",
  "ember.js",
  "backbone.js",
  "redux",
  "mobx",
  "d3.js",
  "three.js",
  "bootstrap",
  "material-ui",
  "ant design",
  "jest",
  "mocha",
  "cypress",
  "puppeteer",
  "axios",
  "fetch api",
  "webpack",
  "babel",
  "eslint",
  "prettier",
  "parcel",
  "rollup",
  "chakra-ui",
  "mui",
  "antd",
  "dom",
  "ajax",
  "restful",
  "spa",
  "ssr",
  "csr",
  "api",
  "promise",
  "callback",
  "async/await",
  "arrow function",
  "destructuring",
  "template literals",
  "class",
  "module",
  "prototype",
  "closure",
  "event loop",
  "hoisting",
  "es7",
  "es8",
  "es9",
  "es10",
  "es11",
  "es12",
  "tc39",
  "ecmascript specification",
  "typescript",
  "flow",
  "webassembly",
  "progressive web apps",
  "serverless",
  "microservices",
  "graphql",
  "docker",
  "kubernetes",
  "functional programming",
  "object-oriented programming",
  "asynchronous programming",
  "test-driven development",
  "behavior-driven development",
  "continuous integration",
  "continuous deployment",
  "agile methodology",
  "scrum",
  "kanban",
  "git",
  "github",
  "gitlab",
  "bitbucket",
  "npm",
  "yarn",
  "package.json",
  "package-lock.json",
  "webpack.config.js",
  "babel.config.js",
  "node_modules",
  "rxjs",
  "vuex",
  "flux",
  "redux-thunk",
  "redux-saga",
  "graphql",
  "apollo-client",
  "apollo-server",
  "graphql-client",
  "graphql-server",
  "graphql-schema",
  "mongodb",
  "mongoose",
  "sequelize",
  "orm",
  "database",
  "nosql",
  "sql",
  "mysql",
  "postgresql",
  "sqlite",
  "mongodb-atlas",
  "firebase",
];

module.exports = jsWords;
